name: CI/CD con Node y Angular

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 18.17.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install project dependencies
        run: npm install

      - name: Build Angular project
        run: ng build --prod

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Deploy to S3 bucket
        run: |
          aws s3 cp --recursive --acl public dist s3://angular-bucket-ayd