name: Angular

on:
  push:
    branches:
      - develop  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --prod
      - name: Install AWS CLI v2
        run: |
          aws s3 cp ./dist/* s3://daveops.co.in

      - name: Deploy to S3
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          npm install -g aws-cli
          aws s3 sync ./dist/libraryng s3://$AWS_S3_BUCKET --delete